dimension: 2
dynamic_obstacles: []
goal_points:
- - 8
  - 14
- - 4
  - 11
- - 6
  - 12
- - 9
  - 15
- - 3
  - 8
- - 18
  - 11
- - 18
  - 10
- - 8
  - 2
- - 2
  - 9
- - 16
  - 13
- - 14
  - 13
- - 11
  - 6
- - 12
  - 0
- - 14
  - 6
- - 16
  - 9
- - 15
  - 11
- - 11
  - 19
- - 3
  - 14
- - 7
  - 3
- - 14
  - 4
- - 14
  - 17
- - 1
  - 8
- - 10
  - 10
- - 11
  - 9
- - 5
  - 17
- - 10
  - 18
- - 19
  - 4
- - 6
  - 16
- - 12
  - 5
- - 12
  - 19
- - 2
  - 5
- - 0
  - 16
- - 17
  - 9
- - 8
  - 4
- - 4
  - 8
- - 15
  - 12
- - 0
  - 2
- - 17
  - 0
- - 12
  - 15
- - 8
  - 5
- - 6
  - 15
- - 9
  - 18
- - 6
  - 2
- - 12
  - 17
- - 7
  - 1
- - 1
  - 0
- - 12
  - 10
- - 10
  - 17
- - 5
  - 18
- - 6
  - 14
- - 11
  - 8
- - 4
  - 14
- - 4
  - 6
- - 5
  - 9
- - 11
  - 3
- - 1
  - 15
- - 6
  - 6
- - 0
  - 19
- - 7
  - 0
- - 10
  - 3
- - 19
  - 6
- - 8
  - 9
- - 18
  - 2
- - 13
  - 1
- - 0
  - 0
- - 0
  - 9
- - 16
  - 11
- - 11
  - 13
- - 2
  - 1
- - 13
  - 17
- - 2
  - 3
- - 17
  - 5
- - 6
  - 0
- - 16
  - 4
- - 9
  - 8
- - 13
  - 8
- - 16
  - 10
- - 5
  - 15
- - 8
  - 0
- - 4
  - 3
- - 2
  - 11
- - 5
  - 6
- - 10
  - 8
- - 19
  - 0
- - 3
  - 10
- - 12
  - 8
- - 3
  - 16
- - 0
  - 18
- - 2
  - 13
- - 11
  - 0
- - 12
  - 7
- - 12
  - 3
- - 16
  - 16
- - 6
  - 4
- - 12
  - 12
- - 10
  - 19
- - 13
  - 7
- - 10
  - 6
- - 6
  - 17
- - 2
  - 0
space_limits:
- 20
- 20
start_points:
- - 14
  - 9
- - 8
  - 17
- - 8
  - 10
- - 5
  - 9
- - 16
  - 14
- - 3
  - 16
- - 19
  - 13
- - 15
  - 11
- - 19
  - 11
- - 19
  - 15
- - 15
  - 9
- - 11
  - 1
- - 2
  - 19
- - 18
  - 7
- - 17
  - 1
- - 4
  - 9
- - 8
  - 2
- - 1
  - 16
- - 14
  - 14
- - 1
  - 0
- - 18
  - 18
- - 16
  - 13
- - 15
  - 4
- - 13
  - 7
- - 10
  - 19
- - 13
  - 13
- - 17
  - 0
- - 17
  - 5
- - 8
  - 18
- - 18
  - 3
- - 0
  - 9
- - 17
  - 9
- - 4
  - 5
- - 9
  - 19
- - 1
  - 6
- - 0
  - 3
- - 7
  - 9
- - 9
  - 13
- - 6
  - 0
- - 15
  - 1
- - 16
  - 17
- - 5
  - 19
- - 7
  - 6
- - 19
  - 19
- - 13
  - 11
- - 15
  - 13
- - 2
  - 13
- - 18
  - 15
- - 19
  - 16
- - 0
  - 10
- - 17
  - 17
- - 12
  - 14
- - 14
  - 3
- - 6
  - 1
- - 1
  - 9
- - 12
  - 8
- - 10
  - 1
- - 0
  - 18
- - 1
  - 5
- - 10
  - 6
- - 3
  - 2
- - 3
  - 13
- - 11
  - 6
- - 0
  - 11
- - 3
  - 4
- - 5
  - 12
- - 18
  - 12
- - 1
  - 18
- - 0
  - 13
- - 16
  - 15
- - 16
  - 0
- - 12
  - 3
- - 15
  - 14
- - 3
  - 7
- - 13
  - 19
- - 1
  - 3
- - 14
  - 15
- - 0
  - 2
- - 9
  - 6
- - 3
  - 0
- - 11
  - 10
- - 18
  - 5
- - 6
  - 16
- - 8
  - 0
- - 13
  - 4
- - 6
  - 7
- - 3
  - 8
- - 15
  - 8
- - 7
  - 1
- - 3
  - 10
- - 3
  - 9
- - 2
  - 3
- - 16
  - 10
- - 6
  - 12
- - 11
  - 17
- - 17
  - 13
- - 14
  - 4
- - 14
  - 12
- - 5
  - 18
- - 11
  - 19
static_obstacles: []
