dimension: 2
dynamic_obstacles: []
goal_point:
- 7
- 7
space_limits:
- 10
- 10
start_point:
- 0
- 6
static_obstacles:
- - 3
  - 2
- - 6
  - 6
- - 7
  - 3
- - 2
  - 6
- - 10
  - 5
- - 10
  - 1
- - 0
  - 9
- - 5
  - 10
- - 3
  - 2
- - 6
  - 7
