dimension: 2
dynamic_obstacles: []
start_points:
- - 0
  - 2
- - 4
  - 2
- - 2
  - 0
- - 2
  - 4
goal_points:
- - 4
  - 2
- - 0
  - 2
- - 2
  - 4
- - 2
  - 0
space_limits:
- 5
- 5
static_obstacles: [
    [0, 4],
    [1, 4],
    [0, 3],
    [1, 3],

    [ 0, 1 ],
    [ 1, 1 ],
    [ 0, 0 ],
    [ 1, 0 ],

    [ 3, 4 ],
    [ 4, 4 ],
    [ 3, 3 ],
    [ 4, 3 ],

    [ 3, 1 ],
    [ 4, 1 ],
    [ 3, 0 ],
    [ 4, 0 ],
]
