dimension: 2
dynamic_obstacles: []
goal_points:
- - 0
  - 0
- - 4
  - 0
space_limits:
- 5
- 2
start_points:
- - 4
  - 0
- - 0
  - 0
static_obstacles: [
    [0, 1],
    [1, 1],
    [3, 1],
    [4, 1],
]
