dimension: 2
dynamic_obstacles: []
goal_points:
- - 15
  - 3
- - 44
  - 8
- - 1
  - 17
- - 25
  - 39
- - 40
  - 11
- - 18
  - 31
- - 39
  - 16
- - 7
  - 26
- - 22
  - 46
- - 45
  - 32
- - 21
  - 48
- - 11
  - 9
- - 2
  - 7
- - 25
  - 20
- - 28
  - 4
- - 22
  - 30
- - 25
  - 32
- - 16
  - 0
- - 11
  - 39
- - 7
  - 40
- - 33
  - 12
- - 43
  - 30
- - 26
  - 27
- - 30
  - 25
- - 8
  - 10
- - 29
  - 12
- - 10
  - 45
- - 14
  - 14
- - 40
  - 3
- - 13
  - 23
space_limits:
- 50
- 50
start_points:
- - 36
  - 41
- - 4
  - 12
- - 34
  - 0
- - 33
  - 36
- - 21
  - 3
- - 40
  - 49
- - 3
  - 7
- - 48
  - 44
- - 37
  - 16
- - 36
  - 8
- - 24
  - 41
- - 5
  - 2
- - 36
  - 37
- - 29
  - 48
- - 21
  - 44
- - 23
  - 43
- - 9
  - 10
- - 19
  - 36
- - 17
  - 29
- - 25
  - 46
- - 30
  - 33
- - 27
  - 35
- - 13
  - 13
- - 15
  - 0
- - 39
  - 40
- - 32
  - 17
- - 48
  - 11
- - 46
  - 13
- - 43
  - 17
- - 43
  - 35
static_obstacles: []
