dimension: 2
dynamic_obstacles: []
goal_points:
- - 24
  - 15
- - 24
  - 23
- - 26
  - 2
- - 15
  - 17
- - 18
  - 1
- - 5
  - 2
- - 25
  - 5
- - 30
  - 31
- - 15
  - 6
- - 20
  - 10
- - 15
  - 24
- - 23
  - 21
- - 16
  - 14
- - 1
  - 8
- - 11
  - 14
- - 25
  - 29
- - 30
  - 18
- - 14
  - 23
- - 30
  - 2
- - 2
  - 7
- - 30
  - 3
- - 26
  - 3
- - 30
  - 16
- - 8
  - 12
- - 0
  - 28
- - 23
  - 27
- - 24
  - 6
- - 20
  - 26
- - 15
  - 11
- - 2
  - 15
- - 18
  - 12
- - 8
  - 5
- - 22
  - 18
- - 25
  - 10
- - 23
  - 4
- - 9
  - 0
- - 10
  - 6
- - 23
  - 24
- - 27
  - 21
- - 27
  - 12
- - 29
  - 2
- - 20
  - 2
- - 28
  - 9
- - 31
  - 29
- - 21
  - 31
- - 27
  - 19
- - 31
  - 28
- - 18
  - 9
- - 7
  - 7
- - 0
  - 5
- - 2
  - 30
- - 22
  - 29
- - 14
  - 0
- - 23
  - 29
- - 28
  - 10
- - 17
  - 7
- - 19
  - 24
- - 14
  - 6
- - 9
  - 23
- - 4
  - 22
- - 14
  - 2
- - 5
  - 25
- - 27
  - 13
- - 25
  - 1
- - 18
  - 3
- - 5
  - 0
- - 20
  - 12
- - 30
  - 9
- - 10
  - 28
- - 28
  - 0
- - 18
  - 14
- - 16
  - 29
- - 31
  - 26
- - 4
  - 21
- - 22
  - 1
- - 3
  - 2
- - 26
  - 8
- - 7
  - 14
- - 8
  - 18
- - 17
  - 26
- - 2
  - 19
- - 21
  - 3
- - 14
  - 27
- - 14
  - 21
- - 21
  - 26
- - 21
  - 8
- - 7
  - 15
- - 29
  - 28
- - 4
  - 23
- - 29
  - 24
- - 18
  - 28
- - 21
  - 30
- - 21
  - 29
- - 21
  - 4
- - 8
  - 4
- - 11
  - 12
- - 24
  - 22
- - 25
  - 6
- - 0
  - 0
- - 25
  - 9
space_limits:
- 32
- 32
start_points:
- - 1
  - 19
- - 25
  - 10
- - 0
  - 4
- - 11
  - 25
- - 11
  - 22
- - 3
  - 12
- - 21
  - 11
- - 9
  - 14
- - 21
  - 27
- - 12
  - 17
- - 1
  - 1
- - 19
  - 26
- - 6
  - 4
- - 25
  - 19
- - 18
  - 6
- - 9
  - 19
- - 17
  - 19
- - 26
  - 28
- - 15
  - 31
- - 0
  - 25
- - 24
  - 27
- - 7
  - 25
- - 21
  - 22
- - 29
  - 23
- - 21
  - 4
- - 21
  - 2
- - 4
  - 18
- - 30
  - 16
- - 2
  - 27
- - 13
  - 30
- - 2
  - 20
- - 18
  - 14
- - 12
  - 13
- - 20
  - 20
- - 4
  - 24
- - 19
  - 27
- - 22
  - 10
- - 11
  - 31
- - 5
  - 16
- - 14
  - 25
- - 9
  - 28
- - 7
  - 17
- - 21
  - 10
- - 0
  - 12
- - 13
  - 1
- - 19
  - 9
- - 7
  - 29
- - 29
  - 1
- - 8
  - 12
- - 13
  - 21
- - 15
  - 19
- - 8
  - 14
- - 16
  - 3
- - 31
  - 11
- - 1
  - 20
- - 1
  - 25
- - 22
  - 18
- - 4
  - 31
- - 16
  - 0
- - 21
  - 29
- - 21
  - 24
- - 30
  - 30
- - 12
  - 0
- - 31
  - 25
- - 15
  - 15
- - 10
  - 28
- - 5
  - 3
- - 16
  - 29
- - 14
  - 0
- - 16
  - 22
- - 30
  - 6
- - 19
  - 14
- - 5
  - 27
- - 20
  - 5
- - 11
  - 1
- - 6
  - 24
- - 21
  - 0
- - 20
  - 24
- - 26
  - 3
- - 14
  - 20
- - 5
  - 11
- - 21
  - 16
- - 20
  - 15
- - 31
  - 30
- - 15
  - 0
- - 2
  - 30
- - 14
  - 31
- - 21
  - 12
- - 21
  - 19
- - 19
  - 13
- - 14
  - 27
- - 21
  - 3
- - 24
  - 23
- - 0
  - 31
- - 23
  - 25
- - 16
  - 9
- - 7
  - 4
- - 28
  - 3
- - 30
  - 9
- - 15
  - 28
static_obstacles: []
