dimension: 2
dynamic_obstacles: []
goal_points:
- - 5
  - 8
- - 5
  - 2
- - 8
  - 9
- - 9
  - 2
- - 8
  - 0
space_limits:
- 10
- 10
start_points:
- - 4
  - 7
- - 6
  - 5
- - 3
  - 9
- - 7
  - 3
- - 9
  - 2
static_obstacles: []
